version = 0.1
[default.deploy.parameters]
stack_name = "student-info-management-system"
resolve_s3 = true
s3_prefix = "student-info-management-system"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "APIName=\"AppSyncApi\" APIStage=\"dev\""
image_repositories = []
